manager/urls.py
from django.urls import path
from . import views


app_name = 'content'

urlpatterns = [
    path('',views.ListHome.as_view(),name='home'),
    
    path('<int:year>/<int:month>/<int:day>/<slug:content>/',views.detail_services,name='detail_services'),

    path('<int:service_id>/share',views.service_request,name='service_share')
]

stom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('manager.urls',namespace='content'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/models.py
from django.db import models

from django.db.models import QuerySet

from django.urls import reverse

from django.utils import timezone

from django.contrib.auth.models import User


class PublishedManager(models.Manager):

    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Content.Status.PUBLISHED)
    

class Content(models.Model):


    class Status(models.TextChoices):

        DRAFT = 'DF','DRAFT'
        PUBLISHED = 'PB','PUBLISHED'




    title = models.CharField(max_length=250)

    slug = models.SlugField(max_length=250,unique_for_date='publish')

    body = models.TextField()

    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='content_posts',null=True)

    image = models.ImageField(upload_to='media/content')

    publish = models.DateTimeField(timezone.now)

    status = models.CharField(max_length=2,choices=Status.choices,
                              default=Status.DRAFT)

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    published = PublishedManager()

    objects = models.Manager()

    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish'])
        ]

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('content:detail_services',args=[self.publish.year,
                                               self.publish.month,
                                               self.publish.day,
                                               self.slug])
        


class Comment(models.Model):

    content = models.ForeignKey(Content,on_delete=models.CASCADE,
                                related_name='comments')
    
    name = models.CharField(max_length=85)

    body = models.TextField()

    email = models.EmailField()

    created = models.DateTimeField(auto_now_add=True)

    updated = models.DateTimeField(auto_now=True)

    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self) -> str:
        return f"comment {self.name} or {self.content}"

manager/forms.py
from django import forms

from .models import Comment




class EmailForm(forms.Form):

    name = forms.CharField(max_length=25)

    email = forms.EmailField()

    to = forms.EmailField()

    
    comments = forms.CharField(required=False,
                                                 widget=forms.Textarea)

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ['name','email','body']

manager/views.py
from email.mime.multipart import MIMEMultipart
from django.shortcuts import render,get_object_or_404

from django.views.generic import ListView

from django.views.decorators.http import require_POST

from .models import Content

from .forms import CommentForm,EmailForm

from django.core.mail import send_mail

from django.template.loader import render_to_string







class ListHome(ListView):

    queryset = Content.published.all()

    context_object_name = 'contents'

    template_name = 'content/event/list.html'

    





def detail_services(request,content,year,month,day):

    detail = get_object_or_404(Content,
                               status = Content.Status.PUBLISHED,
                               publish__year= year,
                               publish__month=month,
                               publish__day = day,
                               slug = content)
    
    return render(request,'content/event/detail.html',{'detail':detail})



def service_request(request,service_id):

    service_application = get_object_or_404(Content,id=service_id,status = Content.Status.PUBLISHED)

    sent = False

    if request.method=='POST':

        form_share = EmailForm(request.POST)

        if form_share.is_valid():
            
            cd = form_share.cleaned_data

            post_url = request.build_absolute_uri(service_application.get_absolute_url())

            subject = f"{cd['name']} recommends you read {service_application.title}"

            message = f"Read {service_application.title} at {post_url}\n\n"
            f" {cd['name']} comments: {cd['comments']}"
        
            send_mail(subject,message,'',
                      [cd['to']])

            sent = True





    else:
        form_share = EmailForm()

    return render(request,'content/event/share.html',{'service_application':service_application,
                                                      'sent':sent,
                                                      'form_share':form_share})




def comment_service(request,service_id):
    pass

manager/templates/content/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/stom.css" %}" rel="stylesheet">
</head>
<body>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>


    <div id="sidebar">
        <h2>Зубная ведьма</h2>
        <p>20 лет ломаем дрелью ваши ебучие зубы</p>
    </div>
</body>
</html>

manager/templates/content/event/detail.html
{% extends "content/base.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <h1>{{ detail.title }}</h1>
  <p class="date">
    Published {{ detail.publish }} by {{ detail.author }}
  </p>
  {{ detail.body|linebreaks }}
  <p>
    <a href="{% url "content:service_share" detail.id %}">
      Share this post
    </a>
  </p>
 
{% endblock %}

manager/templates/content/event/list.html
{% extends "content/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}

    <h1>My Blog</h1>
    {% for posts in contents %}


    <h2>
        <a href="{{ posts.get_absolute_url }}">
        {{ posts.title }}
        </a>
    
    </h2>


    <p class="date" style="color:#070707; font-family: georgia, serif; font-size: 15px; font-style: italic;">
    Published {{ posts.publish }} by {{ posts.author }}
    </p>
    {{ posts.body|truncatewords:30|linebreaks }}
    {% endfor %}
    
{% endblock %}

manager/templates/content/event/share.html
{% extends "content/base.html" %}


{% block title %}Share a post{% endblock %}
    {% block content %}
        {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ service_application.title }}" was successfully sent
            to {{ form_share.cleaned_data.to }}.
        </p>
    {% else %}
    <h1>Share "{{ service_application.title }}" by e-mail</h1>
        <form method="post">
    {{form_share.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
    </form>
    {% endif %}
    {% endblock %}